name: Test login

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  hostname: '137.117.195.215'

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login with SSH key and run few commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.hostname }}
          port: 22
          username: emarciunas
          key: "${{ secrets.PRIVATEKEY2 }}"
          script_stop: true     # Stop script after first failure
          script: |
            hostname
            go version
